export enum CommandType {
  TURN_LEFT = 'TURN_LEFT',
  TURN_RIGHT = 'TURN_RIGHT',
  FORWARD = 'FORWARD',
  BACKWARD = 'BACKWARD',
  FOLLOW_LINE_MODE = 'FOLLOW_LINE_MODE',
  TURN_LEFT_FOR_OBSTACLE_AVOID = 'TURN_LEFT_FOR_OBSTACLE_AVOID',
  TURN_RIGHT_FOR_OBSTACLE_AVOID = 'TURN_RIGHT_FOR_OBSTACLE_AVOID',
  STOP = 'STOP',
  MANUAL = 'MANUAL',
  AUTO = 'AUTO',
  AWAIT = 'AWAIT',
}
